# Generated by Django 4.2.3 on 2023-08-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1992-01-10'),
            preserve_default=False,
        ),
    ]
